
export const eventsTypes = {
  ADD_EVENT: 'ADD_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT',  
  SELECT_EVENT: 'SELECT_EVENT',
  LOADING_EVENTS: 'LOADING_EVENTS',
  GET_EVENTS: 'GET_EVENTS',
}